[tool.poetry]
name = "osb-gilder"
version = "0.1.0"
description = "MoF Project for the processing (\"gilding\") of OSB .xlsx files"
authors = ["karbyshevillia <158076825+karbyshevillia@users.noreply.github.com>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
openpyxl = "^3.1.5"
pandas = "^3.0.2"
tkinterdnd2 = "^0.4.3"
ttkbootstrap = "^1.20.2"
customtkinter = "^5.2.2"
pathlib = "^1.0.1"
python-calamine = "^0.6.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
